#!/bin/bash
# Check the signature of the commit just created
# for additional info on --format and "%G?" look for git log --help and check section PRETTY FORMATS
status=$(git log -1 --format="%G?")

if [[ "$status" != "G" ]]; then
    echo "--------------------------------------------------------"
    echo "WARNING: The commit you just made is NOT signed!"
    echo "GitHub rules will block this from being merged."
    echo "Fix it now with: git commit --amend --no-edit -S"
    echo "--------------------------------------------------------"
fi
