name: C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libgtest-dev

    - name: Configure CMake
      run: cmake -S . -B build -DCMAKE_TOOLCHAIN_FILE=code/gcc_x64_toolchain.cmake

    - name: Build
      run: cmake --build build

    - name: Run Tests
      run: |
        cd build
        ctest --output-on-failure

    - name: Check Formatting
      run: |
        # This will fail the build if the code doesn't match the .clang-format file
        find code -name '*.c' -o -name '*.cpp' -o -name '*.h' -o -name '*.hpp' | xargs clang-format --dry-run --Werror